# SwiftLint Configuration for Prosperly
# Enforces coding standards and best practices

# Directories to include in linting
included:
  - Prosperly
  - ProsperlyTests
  - ProsperlyUITests

# Directories to exclude from linting
excluded:
  - Pods
  - .build
  - DerivedData
  - .git

# Enabled rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # Allow TODO comments during development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Custom rules
custom_rules:
  # Require MARK comments for organization
  mark_comments:
    name: "MARK Comments"
    regex: '(class|struct|enum|extension|protocol)\s+\w+[^{]*\{'
    message: "Types should be preceded by a MARK comment"
    severity: warning
    
  # Prevent force unwrapping in production code
  no_force_unwrap:
    name: "Force Unwrap"
    regex: '\!\s*(?!\=)'
    message: "Avoid force unwrapping - use safe unwrapping instead"
    severity: warning
    included: ".*\\.swift"
    excluded: ".*Tests\\.swift"
    
  # Ensure proper documentation
  documentation_required:
    name: "Documentation Required"
    regex: '(public|open)\s+(class|struct|enum|func|var|let)'
    message: "Public declarations should have documentation"
    severity: warning

# Reporter type for CI/CD
reporter: "github-actions-logging"

# Warnings vs errors
warning_threshold: 15
error_threshold: 25 